// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: accounts.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const accountByBrokerUserID = `-- name: AccountByBrokerUserID :one
SELECT id, role, api_secret FROM accounts WHERE broker_user_id = $1
`

type AccountByBrokerUserIDRow struct {
	ID        uuid.UUID
	Role      string
	ApiSecret string
}

func (q *Queries) AccountByBrokerUserID(ctx context.Context, brokerUserID string) (AccountByBrokerUserIDRow, error) {
	row := q.db.QueryRow(ctx, accountByBrokerUserID, brokerUserID)
	var i AccountByBrokerUserIDRow
	err := row.Scan(&i.ID, &i.Role, &i.ApiSecret)
	return i, err
}

const accountRole = `-- name: AccountRole :one
SELECT role FROM accounts WHERE id = $1
`

func (q *Queries) AccountRole(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, accountRole, id)
	var role string
	err := row.Scan(&role)
	return role, err
}

const accounts = `-- name: Accounts :many
SELECT a.id, a.role, a.broker, a.broker_user_id, a.active, a.status,
       f.master_id, f.capital_ratio, f.max_qty_per_order,
       COALESCE(f.enabled, true) AS enabled
FROM accounts a
LEFT JOIN follow_links f ON f.follower_id = a.id
WHERE $1::uuid[] IS NULL OR a.id = ANY($1::uuid[])
ORDER BY a.role, a.broker_user_id
`

type AccountsRow struct {
	ID             uuid.UUID
	Role           string
	Broker         string
	BrokerUserID   string
	Active         bool
	Status         string
	MasterID       pgtype.UUID
	CapitalRatio   decimal.NullDecimal
	MaxQtyPerOrder *int32
	Enabled        bool
}

func (q *Queries) Accounts(ctx context.Context, ids []uuid.UUID) ([]AccountsRow, error) {
	rows, err := q.db.Query(ctx, accounts, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AccountsRow
	for rows.Next() {
		var i AccountsRow
		if err := rows.Scan(
			&i.ID,
			&i.Role,
			&i.Broker,
			&i.BrokerUserID,
			&i.Active,
			&i.Status,
			&i.MasterID,
			&i.CapitalRatio,
			&i.MaxQtyPerOrder,
			&i.Enabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createAccount = `-- name: CreateAccount :exec
INSERT INTO accounts (id, role, broker, broker_user_id, api_secret) VALUES ($1, $2, $3, $4, $5)
`

type CreateAccountParams struct {
	ID           uuid.UUID
	Role         string
	Broker       string
	BrokerUserID string
	ApiSecret    string
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) error {
	_, err := q.db.Exec(ctx, createAccount,
		arg.ID,
		arg.Role,
		arg.Broker,
		arg.BrokerUserID,
		arg.ApiSecret,
	)
	return err
}

const deleteAccount = `-- name: DeleteAccount :execrows
DELETE FROM accounts WHERE id = $1
`

func (q *Queries) DeleteAccount(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAccount, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const masterActive = `-- name: MasterActive :one
SELECT active FROM accounts WHERE id = $1 AND role = 'master'
`

func (q *Queries) MasterActive(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, masterActive, id)
	var active bool
	err := row.Scan(&active)
	return active, err
}

const setAccountActive = `-- name: SetAccountActive :execrows
UPDATE accounts SET active = $2, updated_at = now() WHERE id = $1
`

type SetAccountActiveParams struct {
	ID     uuid.UUID
	Active bool
}

func (q *Queries) SetAccountActive(ctx context.Context, arg SetAccountActiveParams) (int64, error) {
	result, err := q.db.Exec(ctx, setAccountActive, arg.ID, arg.Active)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setAccountStatus = `-- name: SetAccountStatus :execrows
UPDATE accounts SET status = $2, updated_at = now() WHERE id = $1
`

type SetAccountStatusParams struct {
	ID     uuid.UUID
	Status string
}

func (q *Queries) SetAccountStatus(ctx context.Context, arg SetAccountStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, setAccountStatus, arg.ID, arg.Status)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateFollowLinkTerms = `-- name: UpdateFollowLinkTerms :execrows
UPDATE follow_links SET capital_ratio = $2, max_qty_per_order = $3 WHERE follower_id = $1
`

type UpdateFollowLinkTermsParams struct {
	FollowerID     uuid.UUID
	CapitalRatio   decimal.Decimal
	MaxQtyPerOrder *int32
}

func (q *Queries) UpdateFollowLinkTerms(ctx context.Context, arg UpdateFollowLinkTermsParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateFollowLinkTerms, arg.FollowerID, arg.CapitalRatio, arg.MaxQtyPerOrder)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
