// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (token_hash, user_id, ip_address, user_agent, expires_at)
VALUES ($1, $2, $3, $4, $5)
`

type CreateSessionParams struct {
	TokenHash string
	UserID    uuid.UUID
	IpAddress *string
	UserAgent *string
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession,
		arg.TokenHash,
		arg.UserID,
		arg.IpAddress,
		arg.UserAgent,
		arg.ExpiresAt,
	)
	return err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO users (id, email, username, name, password_hash, role)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateUserParams struct {
	ID           uuid.UUID
	Email        string
	Username     string
	Name         string
	PasswordHash string
	Role         string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.Username,
		arg.Name,
		arg.PasswordHash,
		arg.Role,
	)
	return err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :execrows
DELETE FROM sessions
WHERE expires_at <= now()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredSessions)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteOtherSessions = `-- name: DeleteOtherSessions :execrows
DELETE FROM sessions
WHERE user_id = $1 AND token_hash != $2
`

type DeleteOtherSessionsParams struct {
	UserID    uuid.UUID
	TokenHash string
}

func (q *Queries) DeleteOtherSessions(ctx context.Context, arg DeleteOtherSessionsParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOtherSessions, arg.UserID, arg.TokenHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSession = `-- name: DeleteSession :execrows
DELETE FROM sessions
WHERE token_hash = $1
`

func (q *Queries) DeleteSession(ctx context.Context, tokenHash string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSession, tokenHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSessionWithUser = `-- name: GetSessionWithUser :one
SELECT s.id AS session_id, s.token_hash, s.user_id, s.ip_address, s.user_agent,
       s.expires_at, s.created_at AS session_created_at, s.last_seen_at,
       u.email, u.username, u.name, u.phone, u.address, u.gst_number, u.role, u.totp_enabled
FROM sessions s
JOIN users u ON u.id = s.user_id
WHERE s.token_hash = $1 AND s.expires_at > now()
`

type GetSessionWithUserRow struct {
	SessionID        int64
	TokenHash        string
	UserID           uuid.UUID
	IpAddress        *string
	UserAgent        *string
	ExpiresAt        pgtype.Timestamptz
	SessionCreatedAt pgtype.Timestamptz
	LastSeenAt       pgtype.Timestamptz
	Email            string
	Username         string
	Name             string
	Phone            string
	Address          string
	GstNumber        string
	Role             string
	TotpEnabled      bool
}

func (q *Queries) GetSessionWithUser(ctx context.Context, tokenHash string) (GetSessionWithUserRow, error) {
	row := q.db.QueryRow(ctx, getSessionWithUser, tokenHash)
	var i GetSessionWithUserRow
	err := row.Scan(
		&i.SessionID,
		&i.TokenHash,
		&i.UserID,
		&i.IpAddress,
		&i.UserAgent,
		&i.ExpiresAt,
		&i.SessionCreatedAt,
		&i.LastSeenAt,
		&i.Email,
		&i.Username,
		&i.Name,
		&i.Phone,
		&i.Address,
		&i.GstNumber,
		&i.Role,
		&i.TotpEnabled,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, username, name, phone, address, gst_number, password_hash, totp_secret, totp_enabled, role, created_at, updated_at
FROM users
WHERE LOWER(email) = LOWER($1)
`

type GetUserByEmailRow struct {
	ID           uuid.UUID
	Email        string
	Username     string
	Name         string
	Phone        string
	Address      string
	GstNumber    string
	PasswordHash string
	TotpSecret   *string
	TotpEnabled  bool
	Role         string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

func (q *Queries) GetUserByEmail(ctx context.Context, lower string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, lower)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.Name,
		&i.Phone,
		&i.Address,
		&i.GstNumber,
		&i.PasswordHash,
		&i.TotpSecret,
		&i.TotpEnabled,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, username, name, phone, address, gst_number, password_hash, totp_secret, totp_enabled, role, created_at, updated_at
FROM users
WHERE id = $1
`

type GetUserByIDRow struct {
	ID           uuid.UUID
	Email        string
	Username     string
	Name         string
	Phone        string
	Address      string
	GstNumber    string
	PasswordHash string
	TotpSecret   *string
	TotpEnabled  bool
	Role         string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.Name,
		&i.Phone,
		&i.Address,
		&i.GstNumber,
		&i.PasswordHash,
		&i.TotpSecret,
		&i.TotpEnabled,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, email, username, name, phone, address, gst_number, password_hash, totp_secret, totp_enabled, role, created_at, updated_at
FROM users
WHERE LOWER(username) = LOWER($1)
`

type GetUserByUsernameRow struct {
	ID           uuid.UUID
	Email        string
	Username     string
	Name         string
	Phone        string
	Address      string
	GstNumber    string
	PasswordHash string
	TotpSecret   *string
	TotpEnabled  bool
	Role         string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

func (q *Queries) GetUserByUsername(ctx context.Context, lower string) (GetUserByUsernameRow, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, lower)
	var i GetUserByUsernameRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.Name,
		&i.Phone,
		&i.Address,
		&i.GstNumber,
		&i.PasswordHash,
		&i.TotpSecret,
		&i.TotpEnabled,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const touchSession = `-- name: TouchSession :execrows
UPDATE sessions
SET last_seen_at = now(), expires_at = $2
WHERE token_hash = $1
`

type TouchSessionParams struct {
	TokenHash string
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) TouchSession(ctx context.Context, arg TouchSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, touchSession, arg.TokenHash, arg.ExpiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users
SET password_hash = $2, updated_at = now()
WHERE id = $1
`

type UpdateUserPasswordParams struct {
	ID           uuid.UUID
	PasswordHash string
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	return err
}

const updateUserProfile = `-- name: UpdateUserProfile :exec
UPDATE users
SET email = $2, username = $3, name = $4, phone = $5, address = $6, gst_number = $7, updated_at = now()
WHERE id = $1
`

type UpdateUserProfileParams struct {
	ID        uuid.UUID
	Email     string
	Username  string
	Name      string
	Phone     string
	Address   string
	GstNumber string
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) error {
	_, err := q.db.Exec(ctx, updateUserProfile,
		arg.ID,
		arg.Email,
		arg.Username,
		arg.Name,
		arg.Phone,
		arg.Address,
		arg.GstNumber,
	)
	return err
}
