// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: follower_orders.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const followerOrdersByMasterFill = `-- name: FollowerOrdersByMasterFill :many
SELECT id, follower_id FROM follower_orders WHERE master_fill_id = $1 ORDER BY id ASC
`

type FollowerOrdersByMasterFillRow struct {
	ID         int64
	FollowerID uuid.UUID
}

func (q *Queries) FollowerOrdersByMasterFill(ctx context.Context, masterFillID int64) ([]FollowerOrdersByMasterFillRow, error) {
	rows, err := q.db.Query(ctx, followerOrdersByMasterFill, masterFillID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FollowerOrdersByMasterFillRow
	for rows.Next() {
		var i FollowerOrdersByMasterFillRow
		if err := rows.Scan(&i.ID, &i.FollowerID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFollowerOrder = `-- name: GetFollowerOrder :one
SELECT id, master_fill_id, follower_id, idempotency_tag, intended_qty, lot_size, sizing_reason,
       placed_qty, broker_order_id, terminal_status, filled_qty, average_price, attempt_count,
       last_error, created_at, updated_at
FROM follower_orders WHERE id = $1
`

func (q *Queries) GetFollowerOrder(ctx context.Context, id int64) (FollowerOrder, error) {
	row := q.db.QueryRow(ctx, getFollowerOrder, id)
	var i FollowerOrder
	err := row.Scan(
		&i.ID,
		&i.MasterFillID,
		&i.FollowerID,
		&i.IdempotencyTag,
		&i.IntendedQty,
		&i.LotSize,
		&i.SizingReason,
		&i.PlacedQty,
		&i.BrokerOrderID,
		&i.TerminalStatus,
		&i.FilledQty,
		&i.AveragePrice,
		&i.AttemptCount,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertFollowerOrder = `-- name: InsertFollowerOrder :one
INSERT INTO follower_orders
  (master_fill_id, follower_id, idempotency_tag, intended_qty, lot_size, sizing_reason)
VALUES ($1,$2,$3,$4,$5,$6)
RETURNING id
`

type InsertFollowerOrderParams struct {
	MasterFillID   int64
	FollowerID     uuid.UUID
	IdempotencyTag string
	IntendedQty    int32
	LotSize        int32
	SizingReason   int32
}

func (q *Queries) InsertFollowerOrder(ctx context.Context, arg InsertFollowerOrderParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertFollowerOrder,
		arg.MasterFillID,
		arg.FollowerID,
		arg.IdempotencyTag,
		arg.IntendedQty,
		arg.LotSize,
		arg.SizingReason,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const updateFollowerOrderFailed = `-- name: UpdateFollowerOrderFailed :exec
UPDATE follower_orders SET terminal_status = $2, last_error = $3, attempt_count = attempt_count + 1, updated_at = now()
WHERE id = $1
`

type UpdateFollowerOrderFailedParams struct {
	ID             int64
	TerminalStatus *string
	LastError      *string
}

func (q *Queries) UpdateFollowerOrderFailed(ctx context.Context, arg UpdateFollowerOrderFailedParams) error {
	_, err := q.db.Exec(ctx, updateFollowerOrderFailed, arg.ID, arg.TerminalStatus, arg.LastError)
	return err
}

const updateFollowerOrderPlaced = `-- name: UpdateFollowerOrderPlaced :exec
UPDATE follower_orders SET broker_order_id = $2, placed_qty = $3, attempt_count = attempt_count + 1, updated_at = now()
WHERE id = $1
`

type UpdateFollowerOrderPlacedParams struct {
	ID            int64
	BrokerOrderID *string
	PlacedQty     *int32
}

func (q *Queries) UpdateFollowerOrderPlaced(ctx context.Context, arg UpdateFollowerOrderPlacedParams) error {
	_, err := q.db.Exec(ctx, updateFollowerOrderPlaced, arg.ID, arg.BrokerOrderID, arg.PlacedQty)
	return err
}

const updateFollowerOrderStatus = `-- name: UpdateFollowerOrderStatus :one
UPDATE follower_orders
SET terminal_status = $2, filled_qty = $3, average_price = $4, updated_at = now()
WHERE broker_order_id = $1
RETURNING id
`

type UpdateFollowerOrderStatusParams struct {
	BrokerOrderID  *string
	TerminalStatus *string
	FilledQty      int32
	AveragePrice   decimal.NullDecimal
}

func (q *Queries) UpdateFollowerOrderStatus(ctx context.Context, arg UpdateFollowerOrderStatusParams) (int64, error) {
	row := q.db.QueryRow(ctx, updateFollowerOrderStatus,
		arg.BrokerOrderID,
		arg.TerminalStatus,
		arg.FilledQty,
		arg.AveragePrice,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
