// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: follow_links.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const createFollowLink = `-- name: CreateFollowLink :exec
INSERT INTO follow_links (follower_id, master_id, capital_ratio, max_qty_per_order, enabled)
VALUES ($1, $2, $3, $4, $5)
`

type CreateFollowLinkParams struct {
	FollowerID     uuid.UUID
	MasterID       uuid.UUID
	CapitalRatio   decimal.Decimal
	MaxQtyPerOrder *int32
	Enabled        bool
}

func (q *Queries) CreateFollowLink(ctx context.Context, arg CreateFollowLinkParams) error {
	_, err := q.db.Exec(ctx, createFollowLink,
		arg.FollowerID,
		arg.MasterID,
		arg.CapitalRatio,
		arg.MaxQtyPerOrder,
		arg.Enabled,
	)
	return err
}

const deleteFollowLink = `-- name: DeleteFollowLink :execrows
DELETE FROM follow_links WHERE follower_id = $1
`

func (q *Queries) DeleteFollowLink(ctx context.Context, followerID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteFollowLink, followerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const enabledFollowLinks = `-- name: EnabledFollowLinks :many
SELECT follower_id, master_id, capital_ratio, COALESCE(max_qty_per_order, 0) AS max_qty_per_order, enabled, effective_from
FROM follow_links WHERE master_id = $1 AND enabled = true
`

type EnabledFollowLinksRow struct {
	FollowerID     uuid.UUID
	MasterID       uuid.UUID
	CapitalRatio   decimal.Decimal
	MaxQtyPerOrder int32
	Enabled        bool
	EffectiveFrom  pgtype.Timestamptz
}

func (q *Queries) EnabledFollowLinks(ctx context.Context, masterID uuid.UUID) ([]EnabledFollowLinksRow, error) {
	rows, err := q.db.Query(ctx, enabledFollowLinks, masterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EnabledFollowLinksRow
	for rows.Next() {
		var i EnabledFollowLinksRow
		if err := rows.Scan(
			&i.FollowerID,
			&i.MasterID,
			&i.CapitalRatio,
			&i.MaxQtyPerOrder,
			&i.Enabled,
			&i.EffectiveFrom,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const masterIDForFollower = `-- name: MasterIDForFollower :one
SELECT master_id FROM follow_links WHERE follower_id = $1
`

func (q *Queries) MasterIDForFollower(ctx context.Context, followerID uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, masterIDForFollower, followerID)
	var master_id uuid.UUID
	err := row.Scan(&master_id)
	return master_id, err
}

const setFollowLinkEnabled = `-- name: SetFollowLinkEnabled :execrows
UPDATE follow_links SET enabled = $2 WHERE follower_id = $1
`

type SetFollowLinkEnabledParams struct {
	FollowerID uuid.UUID
	Enabled    bool
}

func (q *Queries) SetFollowLinkEnabled(ctx context.Context, arg SetFollowLinkEnabledParams) (int64, error) {
	result, err := q.db.Exec(ctx, setFollowLinkEnabled, arg.FollowerID, arg.Enabled)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
