// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: follower_orders.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const countClosedFollowerOrders = `-- name: CountClosedFollowerOrders :one
SELECT COUNT(*) FROM follower_orders fo
WHERE fo.follower_id = $1 AND fo.terminal_status = 'COMPLETE'
`

func (q *Queries) CountClosedFollowerOrders(ctx context.Context, followerID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countClosedFollowerOrders, followerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOpenFollowerOrders = `-- name: CountOpenFollowerOrders :one
SELECT COUNT(*) FROM follower_orders fo
WHERE fo.follower_id = $1 AND fo.terminal_status IS NULL AND fo.intended_qty > 0
`

func (q *Queries) CountOpenFollowerOrders(ctx context.Context, followerID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countOpenFollowerOrders, followerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRejectedFollowerOrders = `-- name: CountRejectedFollowerOrders :one
SELECT COUNT(*) FROM follower_orders fo
WHERE fo.follower_id = $1 AND (fo.terminal_status IN ('REJECTED', 'CANCELLED', 'DEAD_LETTERED', 'dead_lettered', 'FAILED', 'error', 'failed', '') OR fo.intended_qty = 0 OR (fo.last_error IS NOT NULL AND fo.last_error != ''))
`

func (q *Queries) CountRejectedFollowerOrders(ctx context.Context, followerID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countRejectedFollowerOrders, followerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const followerOrderTerminalExists = `-- name: FollowerOrderTerminalExists :one
SELECT EXISTS(
  SELECT 1 FROM follower_orders
  WHERE follower_id = $1 AND broker_order_id = $2 AND terminal_status IS NOT NULL
)
`

type FollowerOrderTerminalExistsParams struct {
	FollowerID    uuid.UUID
	BrokerOrderID *string
}

func (q *Queries) FollowerOrderTerminalExists(ctx context.Context, arg FollowerOrderTerminalExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, followerOrderTerminalExists, arg.FollowerID, arg.BrokerOrderID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const followerOrdersByMasterFill = `-- name: FollowerOrdersByMasterFill :many
SELECT id, follower_id FROM follower_orders WHERE master_fill_id = $1 ORDER BY id ASC
`

type FollowerOrdersByMasterFillRow struct {
	ID         int64
	FollowerID uuid.UUID
}

func (q *Queries) FollowerOrdersByMasterFill(ctx context.Context, masterFillID *int64) ([]FollowerOrdersByMasterFillRow, error) {
	rows, err := q.db.Query(ctx, followerOrdersByMasterFill, masterFillID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FollowerOrdersByMasterFillRow{}
	for rows.Next() {
		var i FollowerOrdersByMasterFillRow
		if err := rows.Scan(&i.ID, &i.FollowerID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFollowerOrder = `-- name: GetFollowerOrder :one
SELECT id, master_fill_id, follower_id, idempotency_tag, intended_qty, lot_size, sizing_reason,
       placed_qty, broker_order_id, terminal_status, filled_qty, average_price, attempt_count,
       last_error, origin, tradingsymbol, exchange, product, transaction_type, order_type,
       created_at, updated_at
FROM follower_orders WHERE id = $1
`

func (q *Queries) GetFollowerOrder(ctx context.Context, id int64) (FollowerOrder, error) {
	row := q.db.QueryRow(ctx, getFollowerOrder, id)
	var i FollowerOrder
	err := row.Scan(
		&i.ID,
		&i.MasterFillID,
		&i.FollowerID,
		&i.IdempotencyTag,
		&i.IntendedQty,
		&i.LotSize,
		&i.SizingReason,
		&i.PlacedQty,
		&i.BrokerOrderID,
		&i.TerminalStatus,
		&i.FilledQty,
		&i.AveragePrice,
		&i.AttemptCount,
		&i.LastError,
		&i.Origin,
		&i.Tradingsymbol,
		&i.Exchange,
		&i.Product,
		&i.TransactionType,
		&i.OrderType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertDirectFollowerOrder = `-- name: InsertDirectFollowerOrder :one
INSERT INTO follower_orders
  (follower_id, broker_order_id, idempotency_tag, intended_qty, placed_qty, filled_qty, lot_size, sizing_reason, terminal_status, average_price, origin, tradingsymbol, exchange, product, transaction_type, order_type)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16)
ON CONFLICT (follower_id, broker_order_id) WHERE broker_order_id IS NOT NULL
DO UPDATE SET
  terminal_status = EXCLUDED.terminal_status,
  filled_qty = EXCLUDED.filled_qty,
  average_price = EXCLUDED.average_price,
  updated_at = now()
RETURNING id
`

type InsertDirectFollowerOrderParams struct {
	FollowerID      uuid.UUID
	BrokerOrderID   *string
	IdempotencyTag  string
	IntendedQty     int32
	PlacedQty       *int32
	FilledQty       int32
	LotSize         int32
	SizingReason    int32
	TerminalStatus  *string
	AveragePrice    decimal.NullDecimal
	Origin          string
	Tradingsymbol   string
	Exchange        string
	Product         string
	TransactionType string
	OrderType       string
}

func (q *Queries) InsertDirectFollowerOrder(ctx context.Context, arg InsertDirectFollowerOrderParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertDirectFollowerOrder,
		arg.FollowerID,
		arg.BrokerOrderID,
		arg.IdempotencyTag,
		arg.IntendedQty,
		arg.PlacedQty,
		arg.FilledQty,
		arg.LotSize,
		arg.SizingReason,
		arg.TerminalStatus,
		arg.AveragePrice,
		arg.Origin,
		arg.Tradingsymbol,
		arg.Exchange,
		arg.Product,
		arg.TransactionType,
		arg.OrderType,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertFollowerOrder = `-- name: InsertFollowerOrder :one
INSERT INTO follower_orders
  (master_fill_id, follower_id, idempotency_tag, intended_qty, lot_size, sizing_reason, origin, tradingsymbol, exchange, product, transaction_type, order_type)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12)
RETURNING id
`

type InsertFollowerOrderParams struct {
	MasterFillID    *int64
	FollowerID      uuid.UUID
	IdempotencyTag  string
	IntendedQty     int32
	LotSize         int32
	SizingReason    int32
	Origin          string
	Tradingsymbol   string
	Exchange        string
	Product         string
	TransactionType string
	OrderType       string
}

func (q *Queries) InsertFollowerOrder(ctx context.Context, arg InsertFollowerOrderParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertFollowerOrder,
		arg.MasterFillID,
		arg.FollowerID,
		arg.IdempotencyTag,
		arg.IntendedQty,
		arg.LotSize,
		arg.SizingReason,
		arg.Origin,
		arg.Tradingsymbol,
		arg.Exchange,
		arg.Product,
		arg.TransactionType,
		arg.OrderType,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listClosedFollowerOrdersPaginated = `-- name: ListClosedFollowerOrdersPaginated :many
SELECT fo.id, fo.master_fill_id, fo.follower_id, fo.idempotency_tag, fo.intended_qty,
       fo.lot_size, fo.sizing_reason, fo.placed_qty, fo.broker_order_id, fo.terminal_status,
       fo.filled_qty, fo.average_price, fo.attempt_count, fo.last_error, fo.created_at, fo.updated_at,
       fo.origin,
       COALESCE(NULLIF(fo.tradingsymbol, ''), mf.tradingsymbol, '') AS tradingsymbol,
       COALESCE(NULLIF(fo.exchange, ''), mf.exchange, '') AS exchange,
       COALESCE(NULLIF(fo.transaction_type, ''), mf.transaction_type, '') AS transaction_type,
       COALESCE(NULLIF(fo.product, ''), mf.product, '') AS product,
       COALESCE(NULLIF(fo.order_type, ''), mf.order_type, '') AS order_type,
       mf.order_timestamp AS master_order_timestamp, mf.raw_payload AS master_raw_payload
FROM follower_orders fo
LEFT JOIN master_fills mf ON fo.master_fill_id = mf.id
WHERE fo.follower_id = $1 AND fo.terminal_status = 'COMPLETE'
ORDER BY fo.created_at DESC, fo.id DESC
LIMIT $2 OFFSET $3
`

type ListClosedFollowerOrdersPaginatedParams struct {
	FollowerID uuid.UUID
	Limit      int32
	Offset     int32
}

type ListClosedFollowerOrdersPaginatedRow struct {
	ID                   int64
	MasterFillID         *int64
	FollowerID           uuid.UUID
	IdempotencyTag       string
	IntendedQty          int32
	LotSize              int32
	SizingReason         int32
	PlacedQty            *int32
	BrokerOrderID        *string
	TerminalStatus       *string
	FilledQty            int32
	AveragePrice         decimal.NullDecimal
	AttemptCount         int32
	LastError            *string
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	Origin               string
	Tradingsymbol        string
	Exchange             string
	TransactionType      string
	Product              string
	OrderType            string
	MasterOrderTimestamp pgtype.Timestamptz
	MasterRawPayload     []byte
}

func (q *Queries) ListClosedFollowerOrdersPaginated(ctx context.Context, arg ListClosedFollowerOrdersPaginatedParams) ([]ListClosedFollowerOrdersPaginatedRow, error) {
	rows, err := q.db.Query(ctx, listClosedFollowerOrdersPaginated, arg.FollowerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListClosedFollowerOrdersPaginatedRow{}
	for rows.Next() {
		var i ListClosedFollowerOrdersPaginatedRow
		if err := rows.Scan(
			&i.ID,
			&i.MasterFillID,
			&i.FollowerID,
			&i.IdempotencyTag,
			&i.IntendedQty,
			&i.LotSize,
			&i.SizingReason,
			&i.PlacedQty,
			&i.BrokerOrderID,
			&i.TerminalStatus,
			&i.FilledQty,
			&i.AveragePrice,
			&i.AttemptCount,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Origin,
			&i.Tradingsymbol,
			&i.Exchange,
			&i.TransactionType,
			&i.Product,
			&i.OrderType,
			&i.MasterOrderTimestamp,
			&i.MasterRawPayload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFollowerOrdersWithMasterFillByAccount = `-- name: ListFollowerOrdersWithMasterFillByAccount :many
SELECT fo.id, fo.master_fill_id, fo.follower_id, fo.idempotency_tag, fo.intended_qty,
       fo.lot_size, fo.sizing_reason, fo.placed_qty, fo.broker_order_id, fo.terminal_status,
       fo.filled_qty, fo.average_price, fo.attempt_count, fo.last_error, fo.created_at, fo.updated_at,
       fo.origin,
       COALESCE(NULLIF(fo.tradingsymbol, ''), mf.tradingsymbol, '') AS tradingsymbol,
       COALESCE(NULLIF(fo.exchange, ''), mf.exchange, '') AS exchange,
       COALESCE(NULLIF(fo.transaction_type, ''), mf.transaction_type, '') AS transaction_type,
       COALESCE(NULLIF(fo.product, ''), mf.product, '') AS product,
       COALESCE(NULLIF(fo.order_type, ''), mf.order_type, '') AS order_type,
       mf.order_timestamp AS master_order_timestamp, mf.raw_payload AS master_raw_payload
FROM follower_orders fo
LEFT JOIN master_fills mf ON fo.master_fill_id = mf.id
WHERE fo.follower_id = $1
ORDER BY fo.created_at DESC
LIMIT 100
`

type ListFollowerOrdersWithMasterFillByAccountRow struct {
	ID                   int64
	MasterFillID         *int64
	FollowerID           uuid.UUID
	IdempotencyTag       string
	IntendedQty          int32
	LotSize              int32
	SizingReason         int32
	PlacedQty            *int32
	BrokerOrderID        *string
	TerminalStatus       *string
	FilledQty            int32
	AveragePrice         decimal.NullDecimal
	AttemptCount         int32
	LastError            *string
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	Origin               string
	Tradingsymbol        string
	Exchange             string
	TransactionType      string
	Product              string
	OrderType            string
	MasterOrderTimestamp pgtype.Timestamptz
	MasterRawPayload     []byte
}

func (q *Queries) ListFollowerOrdersWithMasterFillByAccount(ctx context.Context, followerID uuid.UUID) ([]ListFollowerOrdersWithMasterFillByAccountRow, error) {
	rows, err := q.db.Query(ctx, listFollowerOrdersWithMasterFillByAccount, followerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFollowerOrdersWithMasterFillByAccountRow{}
	for rows.Next() {
		var i ListFollowerOrdersWithMasterFillByAccountRow
		if err := rows.Scan(
			&i.ID,
			&i.MasterFillID,
			&i.FollowerID,
			&i.IdempotencyTag,
			&i.IntendedQty,
			&i.LotSize,
			&i.SizingReason,
			&i.PlacedQty,
			&i.BrokerOrderID,
			&i.TerminalStatus,
			&i.FilledQty,
			&i.AveragePrice,
			&i.AttemptCount,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Origin,
			&i.Tradingsymbol,
			&i.Exchange,
			&i.TransactionType,
			&i.Product,
			&i.OrderType,
			&i.MasterOrderTimestamp,
			&i.MasterRawPayload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenFollowerOrdersPaginated = `-- name: ListOpenFollowerOrdersPaginated :many
SELECT fo.id, fo.master_fill_id, fo.follower_id, fo.idempotency_tag, fo.intended_qty,
       fo.lot_size, fo.sizing_reason, fo.placed_qty, fo.broker_order_id, fo.terminal_status,
       fo.filled_qty, fo.average_price, fo.attempt_count, fo.last_error, fo.created_at, fo.updated_at,
       fo.origin,
       COALESCE(NULLIF(fo.tradingsymbol, ''), mf.tradingsymbol, '') AS tradingsymbol,
       COALESCE(NULLIF(fo.exchange, ''), mf.exchange, '') AS exchange,
       COALESCE(NULLIF(fo.transaction_type, ''), mf.transaction_type, '') AS transaction_type,
       COALESCE(NULLIF(fo.product, ''), mf.product, '') AS product,
       COALESCE(NULLIF(fo.order_type, ''), mf.order_type, '') AS order_type,
       mf.order_timestamp AS master_order_timestamp, mf.raw_payload AS master_raw_payload
FROM follower_orders fo
LEFT JOIN master_fills mf ON fo.master_fill_id = mf.id
WHERE fo.follower_id = $1 AND fo.terminal_status IS NULL AND fo.intended_qty > 0
ORDER BY fo.created_at DESC, fo.id DESC
LIMIT $2 OFFSET $3
`

type ListOpenFollowerOrdersPaginatedParams struct {
	FollowerID uuid.UUID
	Limit      int32
	Offset     int32
}

type ListOpenFollowerOrdersPaginatedRow struct {
	ID                   int64
	MasterFillID         *int64
	FollowerID           uuid.UUID
	IdempotencyTag       string
	IntendedQty          int32
	LotSize              int32
	SizingReason         int32
	PlacedQty            *int32
	BrokerOrderID        *string
	TerminalStatus       *string
	FilledQty            int32
	AveragePrice         decimal.NullDecimal
	AttemptCount         int32
	LastError            *string
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	Origin               string
	Tradingsymbol        string
	Exchange             string
	TransactionType      string
	Product              string
	OrderType            string
	MasterOrderTimestamp pgtype.Timestamptz
	MasterRawPayload     []byte
}

func (q *Queries) ListOpenFollowerOrdersPaginated(ctx context.Context, arg ListOpenFollowerOrdersPaginatedParams) ([]ListOpenFollowerOrdersPaginatedRow, error) {
	rows, err := q.db.Query(ctx, listOpenFollowerOrdersPaginated, arg.FollowerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOpenFollowerOrdersPaginatedRow{}
	for rows.Next() {
		var i ListOpenFollowerOrdersPaginatedRow
		if err := rows.Scan(
			&i.ID,
			&i.MasterFillID,
			&i.FollowerID,
			&i.IdempotencyTag,
			&i.IntendedQty,
			&i.LotSize,
			&i.SizingReason,
			&i.PlacedQty,
			&i.BrokerOrderID,
			&i.TerminalStatus,
			&i.FilledQty,
			&i.AveragePrice,
			&i.AttemptCount,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Origin,
			&i.Tradingsymbol,
			&i.Exchange,
			&i.TransactionType,
			&i.Product,
			&i.OrderType,
			&i.MasterOrderTimestamp,
			&i.MasterRawPayload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRejectedFollowerOrdersPaginated = `-- name: ListRejectedFollowerOrdersPaginated :many
SELECT fo.id, fo.master_fill_id, fo.follower_id, fo.idempotency_tag, fo.intended_qty,
       fo.lot_size, fo.sizing_reason, fo.placed_qty, fo.broker_order_id, fo.terminal_status,
       fo.filled_qty, fo.average_price, fo.attempt_count, fo.last_error, fo.created_at, fo.updated_at,
       fo.origin,
       COALESCE(NULLIF(fo.tradingsymbol, ''), mf.tradingsymbol, '') AS tradingsymbol,
       COALESCE(NULLIF(fo.exchange, ''), mf.exchange, '') AS exchange,
       COALESCE(NULLIF(fo.transaction_type, ''), mf.transaction_type, '') AS transaction_type,
       COALESCE(NULLIF(fo.product, ''), mf.product, '') AS product,
       COALESCE(NULLIF(fo.order_type, ''), mf.order_type, '') AS order_type,
       mf.order_timestamp AS master_order_timestamp, mf.raw_payload AS master_raw_payload
FROM follower_orders fo
LEFT JOIN master_fills mf ON fo.master_fill_id = mf.id
WHERE fo.follower_id = $1 AND (fo.terminal_status IN ('REJECTED', 'CANCELLED', 'DEAD_LETTERED', 'dead_lettered', 'FAILED', 'error', 'failed', '') OR fo.intended_qty = 0 OR (fo.last_error IS NOT NULL AND fo.last_error != ''))
ORDER BY fo.created_at DESC, fo.id DESC
LIMIT $2 OFFSET $3
`

type ListRejectedFollowerOrdersPaginatedParams struct {
	FollowerID uuid.UUID
	Limit      int32
	Offset     int32
}

type ListRejectedFollowerOrdersPaginatedRow struct {
	ID                   int64
	MasterFillID         *int64
	FollowerID           uuid.UUID
	IdempotencyTag       string
	IntendedQty          int32
	LotSize              int32
	SizingReason         int32
	PlacedQty            *int32
	BrokerOrderID        *string
	TerminalStatus       *string
	FilledQty            int32
	AveragePrice         decimal.NullDecimal
	AttemptCount         int32
	LastError            *string
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	Origin               string
	Tradingsymbol        string
	Exchange             string
	TransactionType      string
	Product              string
	OrderType            string
	MasterOrderTimestamp pgtype.Timestamptz
	MasterRawPayload     []byte
}

func (q *Queries) ListRejectedFollowerOrdersPaginated(ctx context.Context, arg ListRejectedFollowerOrdersPaginatedParams) ([]ListRejectedFollowerOrdersPaginatedRow, error) {
	rows, err := q.db.Query(ctx, listRejectedFollowerOrdersPaginated, arg.FollowerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRejectedFollowerOrdersPaginatedRow{}
	for rows.Next() {
		var i ListRejectedFollowerOrdersPaginatedRow
		if err := rows.Scan(
			&i.ID,
			&i.MasterFillID,
			&i.FollowerID,
			&i.IdempotencyTag,
			&i.IntendedQty,
			&i.LotSize,
			&i.SizingReason,
			&i.PlacedQty,
			&i.BrokerOrderID,
			&i.TerminalStatus,
			&i.FilledQty,
			&i.AveragePrice,
			&i.AttemptCount,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Origin,
			&i.Tradingsymbol,
			&i.Exchange,
			&i.TransactionType,
			&i.Product,
			&i.OrderType,
			&i.MasterOrderTimestamp,
			&i.MasterRawPayload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pendingFollowerOrders = `-- name: PendingFollowerOrders :many
SELECT id, master_fill_id, follower_id, idempotency_tag, intended_qty, lot_size, sizing_reason,
       placed_qty, broker_order_id, terminal_status, filled_qty, average_price, attempt_count,
       last_error, origin, tradingsymbol, exchange, product, transaction_type, order_type,
       created_at, updated_at
FROM follower_orders
WHERE terminal_status IS NULL AND intended_qty > 0 AND created_at < $1
ORDER BY id ASC
`

func (q *Queries) PendingFollowerOrders(ctx context.Context, createdAt pgtype.Timestamptz) ([]FollowerOrder, error) {
	rows, err := q.db.Query(ctx, pendingFollowerOrders, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FollowerOrder{}
	for rows.Next() {
		var i FollowerOrder
		if err := rows.Scan(
			&i.ID,
			&i.MasterFillID,
			&i.FollowerID,
			&i.IdempotencyTag,
			&i.IntendedQty,
			&i.LotSize,
			&i.SizingReason,
			&i.PlacedQty,
			&i.BrokerOrderID,
			&i.TerminalStatus,
			&i.FilledQty,
			&i.AveragePrice,
			&i.AttemptCount,
			&i.LastError,
			&i.Origin,
			&i.Tradingsymbol,
			&i.Exchange,
			&i.Product,
			&i.TransactionType,
			&i.OrderType,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFollowerOrderByTag = `-- name: UpdateFollowerOrderByTag :one
UPDATE follower_orders
SET broker_order_id = $2, terminal_status = $3, filled_qty = $4, average_price = $5, updated_at = now()
WHERE follower_id = $1 AND idempotency_tag = $6
RETURNING id
`

type UpdateFollowerOrderByTagParams struct {
	FollowerID     uuid.UUID
	BrokerOrderID  *string
	TerminalStatus *string
	FilledQty      int32
	AveragePrice   decimal.NullDecimal
	IdempotencyTag string
}

func (q *Queries) UpdateFollowerOrderByTag(ctx context.Context, arg UpdateFollowerOrderByTagParams) (int64, error) {
	row := q.db.QueryRow(ctx, updateFollowerOrderByTag,
		arg.FollowerID,
		arg.BrokerOrderID,
		arg.TerminalStatus,
		arg.FilledQty,
		arg.AveragePrice,
		arg.IdempotencyTag,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const updateFollowerOrderFailed = `-- name: UpdateFollowerOrderFailed :exec
UPDATE follower_orders SET terminal_status = $2, last_error = $3, attempt_count = attempt_count + 1, updated_at = now()
WHERE id = $1
`

type UpdateFollowerOrderFailedParams struct {
	ID             int64
	TerminalStatus *string
	LastError      *string
}

func (q *Queries) UpdateFollowerOrderFailed(ctx context.Context, arg UpdateFollowerOrderFailedParams) error {
	_, err := q.db.Exec(ctx, updateFollowerOrderFailed, arg.ID, arg.TerminalStatus, arg.LastError)
	return err
}

const updateFollowerOrderPlaced = `-- name: UpdateFollowerOrderPlaced :exec
UPDATE follower_orders SET broker_order_id = $2, placed_qty = $3, attempt_count = attempt_count + 1, updated_at = now()
WHERE id = $1
`

type UpdateFollowerOrderPlacedParams struct {
	ID            int64
	BrokerOrderID *string
	PlacedQty     *int32
}

func (q *Queries) UpdateFollowerOrderPlaced(ctx context.Context, arg UpdateFollowerOrderPlacedParams) error {
	_, err := q.db.Exec(ctx, updateFollowerOrderPlaced, arg.ID, arg.BrokerOrderID, arg.PlacedQty)
	return err
}

const updateFollowerOrderStatus = `-- name: UpdateFollowerOrderStatus :one
UPDATE follower_orders
SET terminal_status = $2, filled_qty = $3, average_price = $4, updated_at = now()
WHERE broker_order_id = $1
RETURNING id
`

type UpdateFollowerOrderStatusParams struct {
	BrokerOrderID  *string
	TerminalStatus *string
	FilledQty      int32
	AveragePrice   decimal.NullDecimal
}

func (q *Queries) UpdateFollowerOrderStatus(ctx context.Context, arg UpdateFollowerOrderStatusParams) (int64, error) {
	row := q.db.QueryRow(ctx, updateFollowerOrderStatus,
		arg.BrokerOrderID,
		arg.TerminalStatus,
		arg.FilledQty,
		arg.AveragePrice,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
