// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: groups.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const groupFollowerRows = `-- name: GroupFollowerRows :many
SELECT a.id, a.broker_user_id, f.enabled, a.status
FROM follow_links f
JOIN accounts a ON a.id = f.follower_id
WHERE f.master_id = $1
ORDER BY a.created_at ASC
`

type GroupFollowerRowsRow struct {
	ID           uuid.UUID
	BrokerUserID string
	Enabled      bool
	Status       string
}

func (q *Queries) GroupFollowerRows(ctx context.Context, masterID uuid.UUID) ([]GroupFollowerRowsRow, error) {
	rows, err := q.db.Query(ctx, groupFollowerRows, masterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GroupFollowerRowsRow
	for rows.Next() {
		var i GroupFollowerRowsRow
		if err := rows.Scan(
			&i.ID,
			&i.BrokerUserID,
			&i.Enabled,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const groupMasterInfo = `-- name: GroupMasterInfo :one
SELECT broker_user_id, active FROM accounts WHERE id = $1 AND role = 'master'
`

type GroupMasterInfoRow struct {
	BrokerUserID string
	Active       bool
}

func (q *Queries) GroupMasterInfo(ctx context.Context, id uuid.UUID) (GroupMasterInfoRow, error) {
	row := q.db.QueryRow(ctx, groupMasterInfo, id)
	var i GroupMasterInfoRow
	err := row.Scan(&i.BrokerUserID, &i.Active)
	return i, err
}

const groups = `-- name: Groups :many
SELECT a.id, a.broker_user_id, a.broker, a.status, a.active,
       COUNT(f.follower_id)::int AS follower_count
FROM accounts a
LEFT JOIN follow_links f ON f.master_id = a.id
WHERE a.role = 'master'
GROUP BY a.id, a.broker_user_id, a.broker, a.status, a.active
ORDER BY a.created_at ASC
`

type GroupsRow struct {
	ID            uuid.UUID
	BrokerUserID  string
	Broker        string
	Status        string
	Active        bool
	FollowerCount int32
}

func (q *Queries) Groups(ctx context.Context) ([]GroupsRow, error) {
	rows, err := q.db.Query(ctx, groups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GroupsRow
	for rows.Next() {
		var i GroupsRow
		if err := rows.Scan(
			&i.ID,
			&i.BrokerUserID,
			&i.Broker,
			&i.Status,
			&i.Active,
			&i.FollowerCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
