// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: groups.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const createGroup = `-- name: CreateGroup :exec
INSERT INTO groups (id, name, master_id)
VALUES ($1, $2, $3)
`

type CreateGroupParams struct {
	ID       uuid.UUID
	Name     string
	MasterID uuid.UUID
}

func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) error {
	_, err := q.db.Exec(ctx, createGroup, arg.ID, arg.Name, arg.MasterID)
	return err
}

const deleteGroup = `-- name: DeleteGroup :execrows
DELETE FROM groups WHERE id = $1
`

func (q *Queries) DeleteGroup(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteGroup, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const groupByID = `-- name: GroupByID :one
SELECT id, name, master_id, created_at, updated_at FROM groups WHERE id = $1
`

func (q *Queries) GroupByID(ctx context.Context, id uuid.UUID) (Group, error) {
	row := q.db.QueryRow(ctx, groupByID, id)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.MasterID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const groupByMasterID = `-- name: GroupByMasterID :one
SELECT id, name, master_id, created_at, updated_at FROM groups WHERE master_id = $1 LIMIT 1
`

func (q *Queries) GroupByMasterID(ctx context.Context, masterID uuid.UUID) (Group, error) {
	row := q.db.QueryRow(ctx, groupByMasterID, masterID)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.MasterID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const groupFollowerRows = `-- name: GroupFollowerRows :many
SELECT a.id, a.name, a.broker_user_id, f.enabled, a.status
FROM follow_links f
JOIN accounts a ON a.id = f.follower_id
WHERE f.group_id = $1
ORDER BY a.created_at ASC
`

type GroupFollowerRowsRow struct {
	ID           uuid.UUID
	Name         string
	BrokerUserID string
	Enabled      bool
	Status       string
}

func (q *Queries) GroupFollowerRows(ctx context.Context, groupID uuid.UUID) ([]GroupFollowerRowsRow, error) {
	rows, err := q.db.Query(ctx, groupFollowerRows, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GroupFollowerRowsRow
	for rows.Next() {
		var i GroupFollowerRowsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.BrokerUserID,
			&i.Enabled,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const groupInfo = `-- name: GroupInfo :one
SELECT g.id, g.name, g.master_id,
       a.broker_user_id AS master_broker_user_id,
       a.name AS master_name,
       a.active AS master_active
FROM groups g
JOIN accounts a ON a.id = g.master_id
WHERE g.id = $1 OR g.master_id = $1
LIMIT 1
`

type GroupInfoRow struct {
	ID                 uuid.UUID
	Name               string
	MasterID           uuid.UUID
	MasterBrokerUserID string
	MasterName         string
	MasterActive       bool
}

func (q *Queries) GroupInfo(ctx context.Context, id uuid.UUID) (GroupInfoRow, error) {
	row := q.db.QueryRow(ctx, groupInfo, id)
	var i GroupInfoRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.MasterID,
		&i.MasterBrokerUserID,
		&i.MasterName,
		&i.MasterActive,
	)
	return i, err
}

const groups = `-- name: Groups :many
SELECT g.id, g.name, g.master_id,
       a.broker_user_id AS master_broker_user_id,
       a.name AS master_name,
       a.broker,
       a.status,
       a.active,
       COUNT(f.follower_id)::int AS follower_count
FROM groups g
JOIN accounts a ON a.id = g.master_id
LEFT JOIN follow_links f ON f.group_id = g.id
GROUP BY g.id, g.name, g.master_id, a.broker_user_id, a.name, a.broker, a.status, a.active
ORDER BY g.created_at ASC
`

type GroupsRow struct {
	ID                 uuid.UUID
	Name               string
	MasterID           uuid.UUID
	MasterBrokerUserID string
	MasterName         string
	Broker             string
	Status             string
	Active             bool
	FollowerCount      int32
}

func (q *Queries) Groups(ctx context.Context) ([]GroupsRow, error) {
	rows, err := q.db.Query(ctx, groups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GroupsRow
	for rows.Next() {
		var i GroupsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.MasterID,
			&i.MasterBrokerUserID,
			&i.MasterName,
			&i.Broker,
			&i.Status,
			&i.Active,
			&i.FollowerCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGroupMaster = `-- name: UpdateGroupMaster :execrows
UPDATE groups SET master_id = $2, updated_at = now() WHERE id = $1
`

type UpdateGroupMasterParams struct {
	ID       uuid.UUID
	MasterID uuid.UUID
}

func (q *Queries) UpdateGroupMaster(ctx context.Context, arg UpdateGroupMasterParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateGroupMaster, arg.ID, arg.MasterID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateGroupName = `-- name: UpdateGroupName :execrows
UPDATE groups SET name = $2, updated_at = now() WHERE id = $1
`

type UpdateGroupNameParams struct {
	ID   uuid.UUID
	Name string
}

func (q *Queries) UpdateGroupName(ctx context.Context, arg UpdateGroupNameParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateGroupName, arg.ID, arg.Name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
