// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: holdings.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const countAccountHoldings = `-- name: CountAccountHoldings :one
SELECT COUNT(*) FROM account_holdings
WHERE account_id = $1
`

func (q *Queries) CountAccountHoldings(ctx context.Context, accountID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countAccountHoldings, accountID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listAccountHoldings = `-- name: ListAccountHoldings :many
SELECT id, account_id, instrument, sellable_quantity, buy_average_price,
       ltp, pnl, action, created_at, updated_at
FROM account_holdings
WHERE account_id = $1
ORDER BY instrument ASC
`

func (q *Queries) ListAccountHoldings(ctx context.Context, accountID uuid.UUID) ([]AccountHolding, error) {
	rows, err := q.db.Query(ctx, listAccountHoldings, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AccountHolding
	for rows.Next() {
		var i AccountHolding
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Instrument,
			&i.SellableQuantity,
			&i.BuyAveragePrice,
			&i.Ltp,
			&i.Pnl,
			&i.Action,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAccountHoldingsPaginated = `-- name: ListAccountHoldingsPaginated :many
SELECT id, account_id, instrument, sellable_quantity, buy_average_price,
       ltp, pnl, action, created_at, updated_at
FROM account_holdings
WHERE account_id = $1
ORDER BY instrument ASC
LIMIT $2 OFFSET $3
`

type ListAccountHoldingsPaginatedParams struct {
	AccountID uuid.UUID
	Limit     int32
	Offset    int32
}

func (q *Queries) ListAccountHoldingsPaginated(ctx context.Context, arg ListAccountHoldingsPaginatedParams) ([]AccountHolding, error) {
	rows, err := q.db.Query(ctx, listAccountHoldingsPaginated, arg.AccountID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AccountHolding
	for rows.Next() {
		var i AccountHolding
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Instrument,
			&i.SellableQuantity,
			&i.BuyAveragePrice,
			&i.Ltp,
			&i.Pnl,
			&i.Action,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAccountHolding = `-- name: UpsertAccountHolding :exec
INSERT INTO account_holdings
  (account_id, instrument, sellable_quantity, buy_average_price, ltp, pnl, action, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, now())
ON CONFLICT (account_id, instrument)
DO UPDATE SET
  sellable_quantity = EXCLUDED.sellable_quantity,
  buy_average_price = EXCLUDED.buy_average_price,
  ltp = EXCLUDED.ltp,
  pnl = EXCLUDED.pnl,
  action = EXCLUDED.action,
  updated_at = now()
`

type UpsertAccountHoldingParams struct {
	AccountID        uuid.UUID
	Instrument       string
	SellableQuantity int32
	BuyAveragePrice  decimal.Decimal
	Ltp              decimal.Decimal
	Pnl              decimal.Decimal
	Action           string
}

func (q *Queries) UpsertAccountHolding(ctx context.Context, arg UpsertAccountHoldingParams) error {
	_, err := q.db.Exec(ctx, upsertAccountHolding,
		arg.AccountID,
		arg.Instrument,
		arg.SellableQuantity,
		arg.BuyAveragePrice,
		arg.Ltp,
		arg.Pnl,
		arg.Action,
	)
	return err
}
