// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: instruments.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const instrumentLotSize = `-- name: InstrumentLotSize :one
SELECT lot_size FROM instruments WHERE exchange = $1 AND tradingsymbol = $2
`

type InstrumentLotSizeParams struct {
	Exchange      string
	Tradingsymbol string
}

func (q *Queries) InstrumentLotSize(ctx context.Context, arg InstrumentLotSizeParams) (int32, error) {
	row := q.db.QueryRow(ctx, instrumentLotSize, arg.Exchange, arg.Tradingsymbol)
	var lot_size int32
	err := row.Scan(&lot_size)
	return lot_size, err
}

const upsertInstrument = `-- name: UpsertInstrument :exec
INSERT INTO instruments (instrument_token, exchange, tradingsymbol, lot_size, tick_size, segment, expiry, refreshed_at)
VALUES ($1,$2,$3,$4,$5,$6,$7, now())
ON CONFLICT (instrument_token) DO UPDATE SET
  exchange = EXCLUDED.exchange, tradingsymbol = EXCLUDED.tradingsymbol,
  lot_size = EXCLUDED.lot_size, tick_size = EXCLUDED.tick_size,
  segment = EXCLUDED.segment, expiry = EXCLUDED.expiry, refreshed_at = now()
`

type UpsertInstrumentParams struct {
	InstrumentToken int64
	Exchange        string
	Tradingsymbol   string
	LotSize         int32
	TickSize        decimal.Decimal
	Segment         *string
	Expiry          pgtype.Date
}

func (q *Queries) UpsertInstrument(ctx context.Context, arg UpsertInstrumentParams) error {
	_, err := q.db.Exec(ctx, upsertInstrument,
		arg.InstrumentToken,
		arg.Exchange,
		arg.Tradingsymbol,
		arg.LotSize,
		arg.TickSize,
		arg.Segment,
		arg.Expiry,
	)
	return err
}
