// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: margins.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const getAccountMargins = `-- name: GetAccountMargins :one
SELECT account_id, net_qty, total_mtm, realized_pnl, account_value, status, updated_at
FROM account_margins
WHERE account_id = $1
`

func (q *Queries) GetAccountMargins(ctx context.Context, accountID uuid.UUID) (AccountMargin, error) {
	row := q.db.QueryRow(ctx, getAccountMargins, accountID)
	var i AccountMargin
	err := row.Scan(
		&i.AccountID,
		&i.NetQty,
		&i.TotalMtm,
		&i.RealizedPnl,
		&i.AccountValue,
		&i.Status,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertAccountMargins = `-- name: UpsertAccountMargins :exec
INSERT INTO account_margins
  (account_id, net_qty, total_mtm, realized_pnl, account_value, status, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, now())
ON CONFLICT (account_id)
DO UPDATE SET
  net_qty = EXCLUDED.net_qty,
  total_mtm = EXCLUDED.total_mtm,
  realized_pnl = EXCLUDED.realized_pnl,
  account_value = EXCLUDED.account_value,
  status = EXCLUDED.status,
  updated_at = now()
`

type UpsertAccountMarginsParams struct {
	AccountID    uuid.UUID
	NetQty       int32
	TotalMtm     decimal.Decimal
	RealizedPnl  decimal.Decimal
	AccountValue decimal.Decimal
	Status       string
}

func (q *Queries) UpsertAccountMargins(ctx context.Context, arg UpsertAccountMarginsParams) error {
	_, err := q.db.Exec(ctx, upsertAccountMargins,
		arg.AccountID,
		arg.NetQty,
		arg.TotalMtm,
		arg.RealizedPnl,
		arg.AccountValue,
		arg.Status,
	)
	return err
}
