// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: master_fills.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const countClosedMasterOrders = `-- name: CountClosedMasterOrders :one
SELECT COUNT(*) FROM master_fills
WHERE master_id = $1 AND status = 'COMPLETE'
`

func (q *Queries) CountClosedMasterOrders(ctx context.Context, masterID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countClosedMasterOrders, masterID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOpenMasterOrders = `-- name: CountOpenMasterOrders :one
SELECT COUNT(*) FROM master_fills
WHERE master_id = $1 AND status NOT IN ('COMPLETE', 'REJECTED', 'CANCELLED')
`

func (q *Queries) CountOpenMasterOrders(ctx context.Context, masterID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countOpenMasterOrders, masterID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRejectedMasterOrders = `-- name: CountRejectedMasterOrders :one
SELECT COUNT(*) FROM master_fills
WHERE master_id = $1 AND status IN ('REJECTED', 'CANCELLED')
`

func (q *Queries) CountRejectedMasterOrders(ctx context.Context, masterID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countRejectedMasterOrders, masterID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertMasterFill = `-- name: InsertMasterFill :one
INSERT INTO master_fills
  (master_id, broker_order_id, exchange, tradingsymbol, instrument_token,
   transaction_type, product, order_type, filled_quantity, average_price,
   status, order_timestamp, raw_payload, dispatch_state)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14)
RETURNING id
`

type InsertMasterFillParams struct {
	MasterID        uuid.UUID
	BrokerOrderID   string
	Exchange        string
	Tradingsymbol   string
	InstrumentToken int64
	TransactionType string
	Product         string
	OrderType       string
	FilledQuantity  int32
	AveragePrice    decimal.Decimal
	Status          string
	OrderTimestamp  pgtype.Timestamptz
	RawPayload      []byte
	DispatchState   string
}

func (q *Queries) InsertMasterFill(ctx context.Context, arg InsertMasterFillParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertMasterFill,
		arg.MasterID,
		arg.BrokerOrderID,
		arg.Exchange,
		arg.Tradingsymbol,
		arg.InstrumentToken,
		arg.TransactionType,
		arg.Product,
		arg.OrderType,
		arg.FilledQuantity,
		arg.AveragePrice,
		arg.Status,
		arg.OrderTimestamp,
		arg.RawPayload,
		arg.DispatchState,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const latestMasterFill = `-- name: LatestMasterFill :one
SELECT id, master_id, broker_order_id, exchange, tradingsymbol, instrument_token,
       transaction_type, product, order_type, filled_quantity, average_price,
       status, order_timestamp, raw_payload
FROM master_fills WHERE master_id = $1
ORDER BY order_timestamp DESC LIMIT 1
`

type LatestMasterFillRow struct {
	ID              int64
	MasterID        uuid.UUID
	BrokerOrderID   string
	Exchange        string
	Tradingsymbol   string
	InstrumentToken int64
	TransactionType string
	Product         string
	OrderType       string
	FilledQuantity  int32
	AveragePrice    decimal.Decimal
	Status          string
	OrderTimestamp  pgtype.Timestamptz
	RawPayload      []byte
}

func (q *Queries) LatestMasterFill(ctx context.Context, masterID uuid.UUID) (LatestMasterFillRow, error) {
	row := q.db.QueryRow(ctx, latestMasterFill, masterID)
	var i LatestMasterFillRow
	err := row.Scan(
		&i.ID,
		&i.MasterID,
		&i.BrokerOrderID,
		&i.Exchange,
		&i.Tradingsymbol,
		&i.InstrumentToken,
		&i.TransactionType,
		&i.Product,
		&i.OrderType,
		&i.FilledQuantity,
		&i.AveragePrice,
		&i.Status,
		&i.OrderTimestamp,
		&i.RawPayload,
	)
	return i, err
}

const listClosedMasterOrdersPaginated = `-- name: ListClosedMasterOrdersPaginated :many
SELECT id, master_id, broker_order_id, exchange, tradingsymbol, instrument_token,
       transaction_type, product, order_type, filled_quantity, average_price,
       status, order_timestamp, raw_payload, received_at, dispatch_state, dispatched_at
FROM master_fills
WHERE master_id = $1 AND status = 'COMPLETE'
ORDER BY order_timestamp DESC, id DESC
LIMIT $2 OFFSET $3
`

type ListClosedMasterOrdersPaginatedParams struct {
	MasterID uuid.UUID
	Limit    int32
	Offset   int32
}

func (q *Queries) ListClosedMasterOrdersPaginated(ctx context.Context, arg ListClosedMasterOrdersPaginatedParams) ([]MasterFill, error) {
	rows, err := q.db.Query(ctx, listClosedMasterOrdersPaginated, arg.MasterID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MasterFill
	for rows.Next() {
		var i MasterFill
		if err := rows.Scan(
			&i.ID,
			&i.MasterID,
			&i.BrokerOrderID,
			&i.Exchange,
			&i.Tradingsymbol,
			&i.InstrumentToken,
			&i.TransactionType,
			&i.Product,
			&i.OrderType,
			&i.FilledQuantity,
			&i.AveragePrice,
			&i.Status,
			&i.OrderTimestamp,
			&i.RawPayload,
			&i.ReceivedAt,
			&i.DispatchState,
			&i.DispatchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMasterFillsByAccount = `-- name: ListMasterFillsByAccount :many
SELECT id, master_id, broker_order_id, exchange, tradingsymbol, instrument_token,
       transaction_type, product, order_type, filled_quantity, average_price,
       status, order_timestamp, raw_payload, received_at, dispatch_state, dispatched_at
FROM master_fills
WHERE master_id = $1
ORDER BY order_timestamp DESC
LIMIT 100
`

func (q *Queries) ListMasterFillsByAccount(ctx context.Context, masterID uuid.UUID) ([]MasterFill, error) {
	rows, err := q.db.Query(ctx, listMasterFillsByAccount, masterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MasterFill
	for rows.Next() {
		var i MasterFill
		if err := rows.Scan(
			&i.ID,
			&i.MasterID,
			&i.BrokerOrderID,
			&i.Exchange,
			&i.Tradingsymbol,
			&i.InstrumentToken,
			&i.TransactionType,
			&i.Product,
			&i.OrderType,
			&i.FilledQuantity,
			&i.AveragePrice,
			&i.Status,
			&i.OrderTimestamp,
			&i.RawPayload,
			&i.ReceivedAt,
			&i.DispatchState,
			&i.DispatchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenMasterOrdersPaginated = `-- name: ListOpenMasterOrdersPaginated :many
SELECT id, master_id, broker_order_id, exchange, tradingsymbol, instrument_token,
       transaction_type, product, order_type, filled_quantity, average_price,
       status, order_timestamp, raw_payload, received_at, dispatch_state, dispatched_at
FROM master_fills
WHERE master_id = $1 AND status NOT IN ('COMPLETE', 'REJECTED', 'CANCELLED')
ORDER BY order_timestamp DESC, id DESC
LIMIT $2 OFFSET $3
`

type ListOpenMasterOrdersPaginatedParams struct {
	MasterID uuid.UUID
	Limit    int32
	Offset   int32
}

func (q *Queries) ListOpenMasterOrdersPaginated(ctx context.Context, arg ListOpenMasterOrdersPaginatedParams) ([]MasterFill, error) {
	rows, err := q.db.Query(ctx, listOpenMasterOrdersPaginated, arg.MasterID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MasterFill
	for rows.Next() {
		var i MasterFill
		if err := rows.Scan(
			&i.ID,
			&i.MasterID,
			&i.BrokerOrderID,
			&i.Exchange,
			&i.Tradingsymbol,
			&i.InstrumentToken,
			&i.TransactionType,
			&i.Product,
			&i.OrderType,
			&i.FilledQuantity,
			&i.AveragePrice,
			&i.Status,
			&i.OrderTimestamp,
			&i.RawPayload,
			&i.ReceivedAt,
			&i.DispatchState,
			&i.DispatchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRejectedMasterOrdersPaginated = `-- name: ListRejectedMasterOrdersPaginated :many
SELECT id, master_id, broker_order_id, exchange, tradingsymbol, instrument_token,
       transaction_type, product, order_type, filled_quantity, average_price,
       status, order_timestamp, raw_payload, received_at, dispatch_state, dispatched_at
FROM master_fills
WHERE master_id = $1 AND status IN ('REJECTED', 'CANCELLED')
ORDER BY order_timestamp DESC, id DESC
LIMIT $2 OFFSET $3
`

type ListRejectedMasterOrdersPaginatedParams struct {
	MasterID uuid.UUID
	Limit    int32
	Offset   int32
}

func (q *Queries) ListRejectedMasterOrdersPaginated(ctx context.Context, arg ListRejectedMasterOrdersPaginatedParams) ([]MasterFill, error) {
	rows, err := q.db.Query(ctx, listRejectedMasterOrdersPaginated, arg.MasterID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MasterFill
	for rows.Next() {
		var i MasterFill
		if err := rows.Scan(
			&i.ID,
			&i.MasterID,
			&i.BrokerOrderID,
			&i.Exchange,
			&i.Tradingsymbol,
			&i.InstrumentToken,
			&i.TransactionType,
			&i.Product,
			&i.OrderType,
			&i.FilledQuantity,
			&i.AveragePrice,
			&i.Status,
			&i.OrderTimestamp,
			&i.RawPayload,
			&i.ReceivedAt,
			&i.DispatchState,
			&i.DispatchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setMasterFillDispatchState = `-- name: SetMasterFillDispatchState :exec
UPDATE master_fills SET dispatch_state = $2, dispatched_at = CASE WHEN $2 = 'dispatched' THEN now() ELSE dispatched_at END
WHERE id = $1
`

type SetMasterFillDispatchStateParams struct {
	ID            int64
	DispatchState string
}

func (q *Queries) SetMasterFillDispatchState(ctx context.Context, arg SetMasterFillDispatchStateParams) error {
	_, err := q.db.Exec(ctx, setMasterFillDispatchState, arg.ID, arg.DispatchState)
	return err
}
