// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: master_fills.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const insertMasterFill = `-- name: InsertMasterFill :one
INSERT INTO master_fills
  (master_id, broker_order_id, exchange, tradingsymbol, instrument_token,
   transaction_type, product, order_type, filled_quantity, average_price,
   status, order_timestamp, raw_payload, dispatch_state)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14)
RETURNING id
`

type InsertMasterFillParams struct {
	MasterID        uuid.UUID
	BrokerOrderID   string
	Exchange        string
	Tradingsymbol   string
	InstrumentToken int64
	TransactionType string
	Product         string
	OrderType       string
	FilledQuantity  int32
	AveragePrice    decimal.Decimal
	Status          string
	OrderTimestamp  pgtype.Timestamptz
	RawPayload      []byte
	DispatchState   string
}

func (q *Queries) InsertMasterFill(ctx context.Context, arg InsertMasterFillParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertMasterFill,
		arg.MasterID,
		arg.BrokerOrderID,
		arg.Exchange,
		arg.Tradingsymbol,
		arg.InstrumentToken,
		arg.TransactionType,
		arg.Product,
		arg.OrderType,
		arg.FilledQuantity,
		arg.AveragePrice,
		arg.Status,
		arg.OrderTimestamp,
		arg.RawPayload,
		arg.DispatchState,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const latestMasterFill = `-- name: LatestMasterFill :one
SELECT id, master_id, broker_order_id, exchange, tradingsymbol, instrument_token,
       transaction_type, product, order_type, filled_quantity, average_price,
       status, order_timestamp, raw_payload
FROM master_fills WHERE master_id = $1
ORDER BY order_timestamp DESC LIMIT 1
`

type LatestMasterFillRow struct {
	ID              int64
	MasterID        uuid.UUID
	BrokerOrderID   string
	Exchange        string
	Tradingsymbol   string
	InstrumentToken int64
	TransactionType string
	Product         string
	OrderType       string
	FilledQuantity  int32
	AveragePrice    decimal.Decimal
	Status          string
	OrderTimestamp  pgtype.Timestamptz
	RawPayload      []byte
}

func (q *Queries) LatestMasterFill(ctx context.Context, masterID uuid.UUID) (LatestMasterFillRow, error) {
	row := q.db.QueryRow(ctx, latestMasterFill, masterID)
	var i LatestMasterFillRow
	err := row.Scan(
		&i.ID,
		&i.MasterID,
		&i.BrokerOrderID,
		&i.Exchange,
		&i.Tradingsymbol,
		&i.InstrumentToken,
		&i.TransactionType,
		&i.Product,
		&i.OrderType,
		&i.FilledQuantity,
		&i.AveragePrice,
		&i.Status,
		&i.OrderTimestamp,
		&i.RawPayload,
	)
	return i, err
}

const setMasterFillDispatchState = `-- name: SetMasterFillDispatchState :exec
UPDATE master_fills SET dispatch_state = $2, dispatched_at = CASE WHEN $2 = 'dispatched' THEN now() ELSE dispatched_at END
WHERE id = $1
`

type SetMasterFillDispatchStateParams struct {
	ID            int64
	DispatchState string
}

func (q *Queries) SetMasterFillDispatchState(ctx context.Context, arg SetMasterFillDispatchStateParams) error {
	_, err := q.db.Exec(ctx, setMasterFillDispatchState, arg.ID, arg.DispatchState)
	return err
}
