// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlcgen

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

type Account struct {
	ID           uuid.UUID
	Role         string
	Broker       string
	BrokerUserID string
	Status       string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	ApiSecret    string
	Active       bool
	Name         string
}

type AccountHolding struct {
	ID               int64
	AccountID        uuid.UUID
	Instrument       string
	SellableQuantity int32
	BuyAveragePrice  decimal.Decimal
	Ltp              decimal.Decimal
	Pnl              decimal.Decimal
	Action           string
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type AccountMargin struct {
	AccountID    uuid.UUID
	NetQty       int32
	TotalMtm     decimal.Decimal
	RealizedPnl  decimal.Decimal
	AccountValue decimal.Decimal
	Status       string
	UpdatedAt    pgtype.Timestamptz
}

type AccountPosition struct {
	ID           int64
	AccountID    uuid.UUID
	Product      string
	Instrument   string
	Quantity     int32
	BuyPrice     decimal.Decimal
	SellPrice    decimal.Decimal
	BuyQuantity  int32
	SellQuantity int32
	Ltp          decimal.Decimal
	Mtm          decimal.Decimal
	Pnl          decimal.Decimal
	Action       string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type FollowLink struct {
	FollowerID     uuid.UUID
	MasterID       uuid.UUID
	CapitalRatio   decimal.Decimal
	MaxQtyPerOrder *int32
	Enabled        bool
	EffectiveFrom  pgtype.Timestamptz
	GroupID        uuid.UUID
}

type FollowerOrder struct {
	ID             int64
	MasterFillID   int64
	FollowerID     uuid.UUID
	IdempotencyTag string
	IntendedQty    int32
	LotSize        int32
	SizingReason   int32
	PlacedQty      *int32
	BrokerOrderID  *string
	TerminalStatus *string
	FilledQty      int32
	AveragePrice   decimal.NullDecimal
	AttemptCount   int32
	LastError      *string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type Group struct {
	ID        uuid.UUID
	Name      string
	MasterID  uuid.UUID
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Instrument struct {
	InstrumentToken int64
	Exchange        string
	Tradingsymbol   string
	LotSize         int32
	TickSize        decimal.Decimal
	Segment         *string
	Expiry          pgtype.Date
	RefreshedAt     pgtype.Timestamptz
}

type MasterFill struct {
	ID              int64
	MasterID        uuid.UUID
	BrokerOrderID   string
	Exchange        string
	Tradingsymbol   string
	InstrumentToken int64
	TransactionType string
	Product         string
	OrderType       string
	FilledQuantity  int32
	AveragePrice    decimal.Decimal
	Status          string
	OrderTimestamp  pgtype.Timestamptz
	RawPayload      []byte
	ReceivedAt      pgtype.Timestamptz
	DispatchState   string
	DispatchedAt    pgtype.Timestamptz
}

type OrderEvent struct {
	ID              int64
	FollowerOrderID *int64
	MasterFillID    *int64
	AccountID       uuid.UUID
	EventType       string
	FromStatus      *string
	ToStatus        *string
	HttpStatus      *int32
	LatencyMs       *int32
	Payload         []byte
	OccurredAt      pgtype.Timestamptz
}
