// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: order_events.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const appendOrderEvent = `-- name: AppendOrderEvent :exec
INSERT INTO order_events (follower_order_id, master_fill_id, account_id, event_type, payload)
VALUES ($1,$2,$3,$4,$5)
`

type AppendOrderEventParams struct {
	FollowerOrderID *int64
	MasterFillID    *int64
	AccountID       uuid.UUID
	EventType       string
	Payload         []byte
}

func (q *Queries) AppendOrderEvent(ctx context.Context, arg AppendOrderEventParams) error {
	_, err := q.db.Exec(ctx, appendOrderEvent,
		arg.FollowerOrderID,
		arg.MasterFillID,
		arg.AccountID,
		arg.EventType,
		arg.Payload,
	)
	return err
}

const orderEventsByFollowerOrder = `-- name: OrderEventsByFollowerOrder :many
SELECT id, follower_order_id, master_fill_id, account_id, event_type, payload, occurred_at
FROM order_events WHERE follower_order_id = $1 ORDER BY id ASC
`

type OrderEventsByFollowerOrderRow struct {
	ID              int64
	FollowerOrderID *int64
	MasterFillID    *int64
	AccountID       uuid.UUID
	EventType       string
	Payload         []byte
	OccurredAt      pgtype.Timestamptz
}

func (q *Queries) OrderEventsByFollowerOrder(ctx context.Context, followerOrderID *int64) ([]OrderEventsByFollowerOrderRow, error) {
	rows, err := q.db.Query(ctx, orderEventsByFollowerOrder, followerOrderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrderEventsByFollowerOrderRow
	for rows.Next() {
		var i OrderEventsByFollowerOrderRow
		if err := rows.Scan(
			&i.ID,
			&i.FollowerOrderID,
			&i.MasterFillID,
			&i.AccountID,
			&i.EventType,
			&i.Payload,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
