// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: positions.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const countClosedPositionsByAccount = `-- name: CountClosedPositionsByAccount :one
SELECT COUNT(*) FROM account_positions
WHERE account_id = $1 AND quantity = 0
`

func (q *Queries) CountClosedPositionsByAccount(ctx context.Context, accountID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countClosedPositionsByAccount, accountID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOpenPositionsByAccount = `-- name: CountOpenPositionsByAccount :one
SELECT COUNT(*) FROM account_positions
WHERE account_id = $1 AND quantity != 0
`

func (q *Queries) CountOpenPositionsByAccount(ctx context.Context, accountID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countOpenPositionsByAccount, accountID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listAccountPositions = `-- name: ListAccountPositions :many
SELECT id, account_id, product, instrument, quantity, buy_price, sell_price,
       buy_quantity, sell_quantity, ltp, mtm, pnl, action, created_at, updated_at
FROM account_positions
WHERE account_id = $1
ORDER BY id ASC
`

func (q *Queries) ListAccountPositions(ctx context.Context, accountID uuid.UUID) ([]AccountPosition, error) {
	rows, err := q.db.Query(ctx, listAccountPositions, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AccountPosition
	for rows.Next() {
		var i AccountPosition
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Product,
			&i.Instrument,
			&i.Quantity,
			&i.BuyPrice,
			&i.SellPrice,
			&i.BuyQuantity,
			&i.SellQuantity,
			&i.Ltp,
			&i.Mtm,
			&i.Pnl,
			&i.Action,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClosedPositionsByAccount = `-- name: ListClosedPositionsByAccount :many
SELECT id, account_id, product, instrument, quantity, buy_price, sell_price,
       buy_quantity, sell_quantity, ltp, mtm, pnl, action, created_at, updated_at
FROM account_positions
WHERE account_id = $1 AND quantity = 0
ORDER BY updated_at DESC, id DESC
LIMIT $2 OFFSET $3
`

type ListClosedPositionsByAccountParams struct {
	AccountID uuid.UUID
	Limit     int32
	Offset    int32
}

func (q *Queries) ListClosedPositionsByAccount(ctx context.Context, arg ListClosedPositionsByAccountParams) ([]AccountPosition, error) {
	rows, err := q.db.Query(ctx, listClosedPositionsByAccount, arg.AccountID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AccountPosition
	for rows.Next() {
		var i AccountPosition
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Product,
			&i.Instrument,
			&i.Quantity,
			&i.BuyPrice,
			&i.SellPrice,
			&i.BuyQuantity,
			&i.SellQuantity,
			&i.Ltp,
			&i.Mtm,
			&i.Pnl,
			&i.Action,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenPositionsByAccount = `-- name: ListOpenPositionsByAccount :many
SELECT id, account_id, product, instrument, quantity, buy_price, sell_price,
       buy_quantity, sell_quantity, ltp, mtm, pnl, action, created_at, updated_at
FROM account_positions
WHERE account_id = $1 AND quantity != 0
ORDER BY updated_at DESC, id DESC
LIMIT $2 OFFSET $3
`

type ListOpenPositionsByAccountParams struct {
	AccountID uuid.UUID
	Limit     int32
	Offset    int32
}

func (q *Queries) ListOpenPositionsByAccount(ctx context.Context, arg ListOpenPositionsByAccountParams) ([]AccountPosition, error) {
	rows, err := q.db.Query(ctx, listOpenPositionsByAccount, arg.AccountID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AccountPosition
	for rows.Next() {
		var i AccountPosition
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Product,
			&i.Instrument,
			&i.Quantity,
			&i.BuyPrice,
			&i.SellPrice,
			&i.BuyQuantity,
			&i.SellQuantity,
			&i.Ltp,
			&i.Mtm,
			&i.Pnl,
			&i.Action,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAccountPosition = `-- name: UpsertAccountPosition :exec
INSERT INTO account_positions
  (account_id, product, instrument, quantity, buy_price, sell_price,
   buy_quantity, sell_quantity, ltp, mtm, pnl, action, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, now())
ON CONFLICT (account_id, product, instrument)
DO UPDATE SET
  quantity = EXCLUDED.quantity,
  buy_price = EXCLUDED.buy_price,
  sell_price = EXCLUDED.sell_price,
  buy_quantity = EXCLUDED.buy_quantity,
  sell_quantity = EXCLUDED.sell_quantity,
  ltp = EXCLUDED.ltp,
  mtm = EXCLUDED.mtm,
  pnl = EXCLUDED.pnl,
  action = EXCLUDED.action,
  updated_at = now()
`

type UpsertAccountPositionParams struct {
	AccountID    uuid.UUID
	Product      string
	Instrument   string
	Quantity     int32
	BuyPrice     decimal.Decimal
	SellPrice    decimal.Decimal
	BuyQuantity  int32
	SellQuantity int32
	Ltp          decimal.Decimal
	Mtm          decimal.Decimal
	Pnl          decimal.Decimal
	Action       string
}

func (q *Queries) UpsertAccountPosition(ctx context.Context, arg UpsertAccountPositionParams) error {
	_, err := q.db.Exec(ctx, upsertAccountPosition,
		arg.AccountID,
		arg.Product,
		arg.Instrument,
		arg.Quantity,
		arg.BuyPrice,
		arg.SellPrice,
		arg.BuyQuantity,
		arg.SellQuantity,
		arg.Ltp,
		arg.Mtm,
		arg.Pnl,
		arg.Action,
	)
	return err
}
