// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: proxy_ips.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const availableProxyIPs = `-- name: AvailableProxyIPs :many
SELECT 
    p.ip_address,
    p.ip_type,
    p.host,
    p.port,
    p.valid_from,
    p.valid_until,
    p.plan,
    p.created_at
FROM proxy_ips p
LEFT JOIN accounts a ON a.ip_address = p.ip_address
WHERE (a.id IS NULL OR ($1::uuid IS NOT NULL AND a.id = $1::uuid))
  AND ($2::text = '' OR p.ip_type = $2::text)
ORDER BY p.ip_address ASC
`

type AvailableProxyIPsParams struct {
	Column1 uuid.UUID
	Column2 string
}

type AvailableProxyIPsRow struct {
	IpAddress  string
	IpType     string
	Host       string
	Port       int32
	ValidFrom  pgtype.Timestamptz
	ValidUntil pgtype.Timestamptz
	Plan       string
	CreatedAt  pgtype.Timestamptz
}

func (q *Queries) AvailableProxyIPs(ctx context.Context, arg AvailableProxyIPsParams) ([]AvailableProxyIPsRow, error) {
	rows, err := q.db.Query(ctx, availableProxyIPs, arg.Column1, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AvailableProxyIPsRow{}
	for rows.Next() {
		var i AvailableProxyIPsRow
		if err := rows.Scan(
			&i.IpAddress,
			&i.IpType,
			&i.Host,
			&i.Port,
			&i.ValidFrom,
			&i.ValidUntil,
			&i.Plan,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProxyIPs = `-- name: ListProxyIPs :many
SELECT 
    p.ip_address,
    p.ip_type,
    p.host,
    p.port,
    p.valid_from,
    p.valid_until,
    p.plan,
    p.created_at,
    a.id AS assigned_account_id,
    a.name AS assigned_account_name
FROM proxy_ips p
LEFT JOIN accounts a ON a.ip_address = p.ip_address
ORDER BY p.ip_type ASC, p.ip_address ASC
`

type ListProxyIPsRow struct {
	IpAddress           string
	IpType              string
	Host                string
	Port                int32
	ValidFrom           pgtype.Timestamptz
	ValidUntil          pgtype.Timestamptz
	Plan                string
	CreatedAt           pgtype.Timestamptz
	AssignedAccountID   *uuid.UUID
	AssignedAccountName *string
}

func (q *Queries) ListProxyIPs(ctx context.Context) ([]ListProxyIPsRow, error) {
	rows, err := q.db.Query(ctx, listProxyIPs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProxyIPsRow{}
	for rows.Next() {
		var i ListProxyIPsRow
		if err := rows.Scan(
			&i.IpAddress,
			&i.IpType,
			&i.Host,
			&i.Port,
			&i.ValidFrom,
			&i.ValidUntil,
			&i.Plan,
			&i.CreatedAt,
			&i.AssignedAccountID,
			&i.AssignedAccountName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const proxyIPByAddress = `-- name: ProxyIPByAddress :one
SELECT 
    p.ip_address,
    p.ip_type,
    p.host,
    p.port,
    p.username,
    p.password,
    p.valid_from,
    p.valid_until,
    p.plan,
    p.created_at
FROM proxy_ips p
WHERE p.ip_address = $1
`

func (q *Queries) ProxyIPByAddress(ctx context.Context, ipAddress string) (ProxyIp, error) {
	row := q.db.QueryRow(ctx, proxyIPByAddress, ipAddress)
	var i ProxyIp
	err := row.Scan(
		&i.IpAddress,
		&i.IpType,
		&i.Host,
		&i.Port,
		&i.Username,
		&i.Password,
		&i.ValidFrom,
		&i.ValidUntil,
		&i.Plan,
		&i.CreatedAt,
	)
	return i, err
}
