// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AccountAuthInfo(ctx context.Context, id uuid.UUID) (AccountAuthInfoRow, error)
	AccountByBrokerUserID(ctx context.Context, brokerUserID string) (AccountByBrokerUserIDRow, error)
	AccountRole(ctx context.Context, id uuid.UUID) (string, error)
	Accounts(ctx context.Context, arg AccountsParams) ([]AccountsRow, error)
	AppendOrderEvent(ctx context.Context, arg AppendOrderEventParams) error
	AvailableProxyIPs(ctx context.Context, arg AvailableProxyIPsParams) ([]AvailableProxyIPsRow, error)
	CountAccountHoldings(ctx context.Context, accountID uuid.UUID) (int64, error)
	CountClosedFollowerOrders(ctx context.Context, followerID uuid.UUID) (int64, error)
	CountClosedMasterOrders(ctx context.Context, masterID uuid.UUID) (int64, error)
	CountClosedPositionsByAccount(ctx context.Context, accountID uuid.UUID) (int64, error)
	CountOpenFollowerOrders(ctx context.Context, followerID uuid.UUID) (int64, error)
	CountOpenMasterOrders(ctx context.Context, masterID uuid.UUID) (int64, error)
	CountOpenPositionsByAccount(ctx context.Context, accountID uuid.UUID) (int64, error)
	CountRejectedFollowerOrders(ctx context.Context, followerID uuid.UUID) (int64, error)
	CountRejectedMasterOrders(ctx context.Context, masterID uuid.UUID) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	CreateAccount(ctx context.Context, arg CreateAccountParams) error
	CreateAccountWithCredentials(ctx context.Context, arg CreateAccountWithCredentialsParams) error
	CreateFollowLink(ctx context.Context, arg CreateFollowLinkParams) error
	CreateGroup(ctx context.Context, arg CreateGroupParams) error
	CreateSession(ctx context.Context, arg CreateSessionParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) error
	DeleteAccount(ctx context.Context, id uuid.UUID) (int64, error)
	DeleteExpiredSessions(ctx context.Context) (int64, error)
	DeleteFollowLink(ctx context.Context, followerID uuid.UUID) (int64, error)
	DeleteGroup(ctx context.Context, id uuid.UUID) (int64, error)
	DeleteOtherSessions(ctx context.Context, arg DeleteOtherSessionsParams) (int64, error)
	DeleteSession(ctx context.Context, tokenHash string) (int64, error)
	EnabledFollowLinks(ctx context.Context, masterID uuid.UUID) ([]EnabledFollowLinksRow, error)
	FollowerOrdersByMasterFill(ctx context.Context, masterFillID int64) ([]FollowerOrdersByMasterFillRow, error)
	GetAccountMargins(ctx context.Context, accountID uuid.UUID) (AccountMargin, error)
	GetFollowerOrder(ctx context.Context, id int64) (FollowerOrder, error)
	GetSessionWithUser(ctx context.Context, tokenHash string) (GetSessionWithUserRow, error)
	GetUserByEmail(ctx context.Context, lower string) (GetUserByEmailRow, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error)
	GetUserByUsername(ctx context.Context, lower string) (GetUserByUsernameRow, error)
	GroupByID(ctx context.Context, id uuid.UUID) (GroupByIDRow, error)
	GroupByMasterID(ctx context.Context, masterID uuid.UUID) (GroupByMasterIDRow, error)
	GroupFollowerRows(ctx context.Context, groupID uuid.UUID) ([]GroupFollowerRowsRow, error)
	GroupIDForFollower(ctx context.Context, followerID uuid.UUID) (uuid.UUID, error)
	GroupInfo(ctx context.Context, arg GroupInfoParams) (GroupInfoRow, error)
	Groups(ctx context.Context, userID *uuid.UUID) ([]GroupsRow, error)
	InsertFollowerOrder(ctx context.Context, arg InsertFollowerOrderParams) (int64, error)
	InsertMasterFill(ctx context.Context, arg InsertMasterFillParams) (int64, error)
	InstrumentLotSize(ctx context.Context, arg InstrumentLotSizeParams) (int32, error)
	LatestMasterFill(ctx context.Context, masterID uuid.UUID) (LatestMasterFillRow, error)
	ListAccountHoldings(ctx context.Context, accountID uuid.UUID) ([]AccountHolding, error)
	ListAccountHoldingsPaginated(ctx context.Context, arg ListAccountHoldingsPaginatedParams) ([]AccountHolding, error)
	ListAccountPositions(ctx context.Context, accountID uuid.UUID) ([]AccountPosition, error)
	ListClosedFollowerOrdersPaginated(ctx context.Context, arg ListClosedFollowerOrdersPaginatedParams) ([]ListClosedFollowerOrdersPaginatedRow, error)
	ListClosedMasterOrdersPaginated(ctx context.Context, arg ListClosedMasterOrdersPaginatedParams) ([]MasterFill, error)
	ListClosedPositionsByAccount(ctx context.Context, arg ListClosedPositionsByAccountParams) ([]AccountPosition, error)
	ListFollowerOrdersWithMasterFillByAccount(ctx context.Context, followerID uuid.UUID) ([]ListFollowerOrdersWithMasterFillByAccountRow, error)
	ListMasterFillsByAccount(ctx context.Context, masterID uuid.UUID) ([]MasterFill, error)
	ListOpenFollowerOrdersPaginated(ctx context.Context, arg ListOpenFollowerOrdersPaginatedParams) ([]ListOpenFollowerOrdersPaginatedRow, error)
	ListOpenMasterOrdersPaginated(ctx context.Context, arg ListOpenMasterOrdersPaginatedParams) ([]MasterFill, error)
	ListOpenPositionsByAccount(ctx context.Context, arg ListOpenPositionsByAccountParams) ([]AccountPosition, error)
	ListProxyIPs(ctx context.Context) ([]ListProxyIPsRow, error)
	ListRejectedFollowerOrdersPaginated(ctx context.Context, arg ListRejectedFollowerOrdersPaginatedParams) ([]ListRejectedFollowerOrdersPaginatedRow, error)
	ListRejectedMasterOrdersPaginated(ctx context.Context, arg ListRejectedMasterOrdersPaginatedParams) ([]MasterFill, error)
	MasterActive(ctx context.Context, id uuid.UUID) (bool, error)
	MasterIDForFollower(ctx context.Context, followerID uuid.UUID) (uuid.UUID, error)
	OrderEventsByFollowerOrder(ctx context.Context, followerOrderID *int64) ([]OrderEventsByFollowerOrderRow, error)
	PendingFollowerOrders(ctx context.Context, createdAt pgtype.Timestamptz) ([]FollowerOrder, error)
	ProxyIPByAddress(ctx context.Context, ipAddress string) (ProxyIp, error)
	SetAccountAPIKey(ctx context.Context, arg SetAccountAPIKeyParams) (int64, error)
	SetAccountAPISecret(ctx context.Context, arg SetAccountAPISecretParams) (int64, error)
	SetAccountAccessToken(ctx context.Context, arg SetAccountAccessTokenParams) (int64, error)
	SetAccountActive(ctx context.Context, arg SetAccountActiveParams) (int64, error)
	SetAccountEncryptedCredentials(ctx context.Context, arg SetAccountEncryptedCredentialsParams) (int64, error)
	SetAccountIPAddress(ctx context.Context, arg SetAccountIPAddressParams) (int64, error)
	SetAccountName(ctx context.Context, arg SetAccountNameParams) (int64, error)
	SetAccountStatus(ctx context.Context, arg SetAccountStatusParams) (int64, error)
	SetFollowLinkEnabled(ctx context.Context, arg SetFollowLinkEnabledParams) (int64, error)
	SetMasterFillDispatchState(ctx context.Context, arg SetMasterFillDispatchStateParams) error
	TouchSession(ctx context.Context, arg TouchSessionParams) (int64, error)
	UpdateFollowLinkTerms(ctx context.Context, arg UpdateFollowLinkTermsParams) (int64, error)
	UpdateFollowerOrderFailed(ctx context.Context, arg UpdateFollowerOrderFailedParams) error
	UpdateFollowerOrderPlaced(ctx context.Context, arg UpdateFollowerOrderPlacedParams) error
	UpdateFollowerOrderStatus(ctx context.Context, arg UpdateFollowerOrderStatusParams) (int64, error)
	UpdateGroupMaster(ctx context.Context, arg UpdateGroupMasterParams) (int64, error)
	UpdateGroupName(ctx context.Context, arg UpdateGroupNameParams) (int64, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) error
	UpsertAccountHolding(ctx context.Context, arg UpsertAccountHoldingParams) error
	UpsertAccountMargins(ctx context.Context, arg UpsertAccountMarginsParams) error
	UpsertAccountPosition(ctx context.Context, arg UpsertAccountPositionParams) error
	UpsertInstrument(ctx context.Context, arg UpsertInstrumentParams) error
}

var _ Querier = (*Queries)(nil)
